name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install   # Adjust this command based on your application's dependencies
      
      - name: Build application
        run: npm run build  # Adjust this command based on your build process

      - name: Deploy to EC2 instance
        uses: easingthemes/deploy-ec2@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}  # Add your SSH key as a secret in your repository
          user: ubuntu  # Adjust the username based on your EC2 instance configuration
          host: ${{ secrets.EC2_HOST }}    # Add your EC2 instance IP or hostname as a secret
          path: /path/to/deploy   # Specify the path where you want to deploy your application on the EC2 instance
