name: Deploy Node.js App

on:
  push:
    branches: [main]  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use a hosted runner

    steps:
      - uses: actions/checkout@v3  # Checkout the repository
      - uses: actions/setup-node@v3  # Set up Node.js environment
        with:
          node-version: 16  # Specify Node.js version
      - run: npm install  # Install dependencies
      - run: npm test  # Run tests (optional)
      - run: npm run build  # Build the application
      - uses: appleboy/ssh-action@master  # Deploy to server (replace with your preferred deployment method)
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /path/to/deploy/directory
            git pull origin main
            npm install
            npm start  # Or your command to start the application
